<%@page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<%@include file="/WEB-INF/common/taglibs.jsp"%>
<div id="footer">
    <div class="footer_service">
        <a href="http://www.yihaodian.com/deliveryinfo/deliveryInfo.do" target="_blank" onclick="addTrackPositionToCookie('1','YHD_HOME_manbai');" ><span class="s1"></span>满百包邮</a><a href="http://www.yihaodian.com/cms/view.do?topicId=18993" target="_blank" onclick="addTrackPositionToCookie('1','YHD_HOME_zhengpin');"><span class="s2"></span>正品保障</a><a href="http://www.yihaodian.com/cms/view.do?topicId=18982" target="_blank" onclick="addTrackPositionToCookie('1','YHD_HOME_shouhou');" ><span class="s3"></span>售后无忧</a>
    </div>
    <p class="footer_link"><a href="http://www.yihaodian.com/cms/view.do?topicId=8101&merchant=1" target="_blank">关于1号店</a>|<a href="http://www.yihaodian.com/cms/view.do?topicId=8121&merchant=1" target="_blank">我们的团队</a>|<a href="http://union.yihaodian.com/passport/login_input.do" target="_blank">网站联盟</a>|<a href="http://www.yihaodian.com/friendlink/index.do" target="_blank">友情链接</a>|<a href="http://www.yihaodian.com/pop-words/index.html" target="_blank">热门搜索</a>|<a href="http://www.yihaodian.com/cms/view.do?topicId=14120&merchant=1" target="_blank">诚征英才</a>|<a href="http://www.yihaodian.com/cms/view.do?topicId=8122&merchant=1" target="_blank">媒体报道</a>|<a href="http://www.yihaodian.com/cmsPage/show.do?pageId=12368" target="_blank">申请成为供应商</a>|<a href="http://supplier.yihaodian.com/" target="_blank">供应商登录/注册</a>|<a class="red_link" href="http://www.zx110.org/cxs/index.html" target="_blank">放心搜</a>|<a href="http://www.yihaodian.com/survey/panel/" target="_blank" tk="YHD_Footer_Link_diaoyan">调研社区</a></p><p><a target="_blank" href="http://www.miibeian.gov.cn/">沪ICP备10215750号</a>| <a target="_blank" href="http://image.yihaodianimg.com/images/licence.JPG">营业执照</a></p><p>Copyright&copy; 1号店网上超市 2007-2013，All Rights Reserved </p>
    <small id="footerbanner2LazyLoad" class="footer_pic_link">
        <a href="https://online.unionpay.com/" target="_blank"><img src="http://image.yihaodianimg.com/front-homepage/global/images/blank.gif" original="http://d6.yihaodianimg.com/N00/M01/1A/30/CgMBmVDzwyaAaIMBAAAJZgSEr6I65200.jpg"></a>
        <a href="http://creditcard.pingan.com/index.shtml" target="_blank"><img src="http://image.yihaodianimg.com/front-homepage/global/images/blank.gif" original="http://d6.yihaodianimg.com/N00/M04/19/A2/CgQCtlDzwg-ADxhpAABCSLsmSeE68100.jpg"></a>
        <a target="_blank" href="https://www.alipay.com/aip/aip_validate_list.htm?trustId=AIP10038885"><img src="http://image.yihaodianimg.com/front-homepage/global/images/blank.gif" original="http://d6.yihaodianimg.com/N01/M06/19/98/CgQCr1Dzwj2AVUL0AAA-ic2BxNw39500.jpg"></a>
        <span><a href="http://www.sgs.gov.cn/lz/licenseLink.do?method=licenceView&entyId=2012100812022553" target="_blank"><img src="http://image.yihaodianimg.com/front-homepage/global/images/blank.gif" original="http://d6.yihaodianimg.com/N01/M08/19/94/CgQCrlDzwnKAUkfSAAAIPrrML6M92400.jpg"></a></span>
        <a target="_blank" href="http://www.police.sh.cn/shga/gweb/email/110/"><img src="http://image.yihaodianimg.com/front-homepage/global/images/blank.gif" original="http://d6.yihaodianimg.com/N00/M05/1A/28/CgMBmFDzwo2AOq1cAAAOMRPod1o78200.jpg"></a>
        <a target="_blank" href="http://www.zx110.org"><img src="http://image.yihaodianimg.com/front-homepage/global/images/blank.gif" original="http://d6.yihaodianimg.com/N02/M05/19/94/CgQCsVDzw0GABUElAADHlvRfNUk94600.jpg"></a>
        <a target="_blank" href="https://search.szfw.org/cert/l/CX20130313002273002387"><img src="http://image.yihaodianimg.com/front-homepage/global/images/blank.gif" original="http://d9.yihaodianimg.com/N03/M06/3A/17/CgQCtFFU7yuAOBnvAAAMYWdn-lg93800.jpg"></a>
    </small>
</div>